services:
  - type: web
    name: supervisor-luna
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_SUPERVISOR_URL
        value: "https://desktop-e6jr4dk.tailc1230a.ts.net/logs"
      - key: VITE_SUPERVISOR_WS
        value: "wss://desktop-e6jr4dk.tailc1230a.ts.net/logs/ws"
